// Generated by CoffeeScript 1.3.3
(function() {
  var Overette;

  $.fn.overette = function(options) {
    var _this = this;
    return this.each(function() {
      var $this;
      $this = $(_this);
      return Overette.initializeTrigger($this, options);
    });
  };

  Overette = {
    dataSrcAttr: 'data-o-src',
    dataTypeAttr: 'data-o-type',
    defaults: {
      popover: {
        position: ["center", "bottom"]
      },
      dialog: {
        position: ["center", "center"]
      },
      dropdown: {
        position: ["center", "bottom"]
      }
    },
    initializeTrigger: function(element, options) {
      return Overette.observeOpenTriggers(element, options);
    },
    observeOpenTriggers: function(element, options) {
      return element.bind('click', function() {
        return Overette.openFromElement(element);
      });
    },
    openFromElement: function(element, options) {
      return Overette.open(element, element.attr(Overette.dataSrcAttr), element.attr(Overette.dataTypeAttr));
    },
    open: function(trigger, src, type, options) {
      var $o;
      if (options == null) {
        options = {};
      }
      $o = Overette[type].init(trigger, src, options);
      if (!Overette.isLoaded($o)) {
        return Overette.retrieveData($o, src, function(err, contents) {
          return Overette[type].replace.call($o, contents.html());
        });
      }
    },
    close: function($o) {
      return Overette.triggerClose($o);
    },
    retrieveData: function($o, src, callback) {
      var $data;
      if (src.charAt(0) === "#") {
        $data = $(src);
        return callback(null, $data);
      } else {
        return callback(new Error("Unsupported Source"));
      }
    },
    isLoaded: function($o) {
      return $o.hasClass("overette-loaded");
    },
    generateUniqueId: function(from) {
      return "overette-ready-" + Math.random().toString(36).substring(7);
    },
    onUpdate: function($o, callback) {
      return $o.bind("overette:update", callback);
    },
    triggerUpdate: function($o) {
      return $o.trigger("overette:update");
    },
    onClose: function($o, callback) {
      return $o.bind("overette:close", callback);
    },
    triggerClose: function($o) {
      return $o.trigger("overette:close");
    },
    popover: {
      init: function(trigger, src, options) {
        var $o;
        if (options == null) {
          options = {};
        }
        $o = $(src);
        if (Overette.isLoaded($o)) {
          $o.fadeIn(100);
          return $o;
        } else {
          $o = Overette.popover.container;
          Overette.popover.setup($o, trigger, $.extend(Overette.defaults.popover, options));
          $('body').append($o);
          $o.fadeIn(100);
          return $o;
        }
      },
      replace: function(contents) {
        this.removeClass("loading");
        this.find(".overette-content").html(contents);
        return Overette.triggerUpdate(this);
      },
      setup: function($o, trigger, options) {
        var _this = this;
        Overette.repositionWhenWindowResized.call($o, trigger, options['position']);
        Overette.closeWhenOverlayClicked.call($o, options);
        Overette.onUpdate($o, function() {
          Overette.repositionAroundTrigger.call($o, trigger, options);
          return $o.addClass("overette-loaded").removeClass("loading");
        });
        Overette.onClose($o, function() {
          return $o.fadeOut(100);
        });
        $o.attr("id", Overette.generateUniqueId(trigger.attr(Overette.dataSrcAttr)));
        return trigger.attr(Overette.dataSrcAttr, "#" + $o.attr("id"));
      },
      container: $("<div class=\"overette-container overette-popover loading not-ready\"><div class=\"overette-overlay\"> </div><div class=\"overette-arrow\"> </div><div class=\"overette-content\"> </div></div>")
    },
    dialog: {
      replace: function($o, contents, options) {
        if (options == null) {
          options = {};
        }
        return console.log("opening dialog");
      }
    },
    dropdown: {
      replace: function($o, contents, options) {
        if (options == null) {
          options = {};
        }
        return console.log("opening dropdown");
      }
    },
    closeWhenOverlayClicked: function(options) {
      var _this = this;
      return this.find(".overette-overlay").bind("click", function() {
        return Overette.close(_this);
      });
    },
    repositionWhenWindowResized: function(trigger, options) {
      var _this = this;
      $(window).resize(function() {
        return Overette.repositionAroundTrigger.call(_this, trigger, options);
      });
      return Overette.repositionAroundTrigger.call(this, trigger, options);
    },
    repositionAroundTrigger: function(trigger, options) {
      var arrow_width, base_left, content_width, coordinates;
      coordinates = trigger.offset();
      content_width = this.find('.overette-content').outerWidth();
      arrow_width = this.find(".overette-arrow").outerWidth();
      base_left = coordinates.left + trigger.outerWidth() / 2;
      coordinates.left = base_left - content_width / 2;
      if (coordinates.left < 0) {
        coordinates.left = 0;
      }
      this.find('.overette-content').css('left', coordinates.left).css('top', coordinates.top + trigger.height() + this.find('.overette-arrow').height() - 1);
      return this.find('.overette-arrow').css('left', base_left - arrow_width / 2);
    }
  };

}).call(this);
